### ISSUE TITLE
Ultrawide screen issue

### ISSUE THREAD

**Issue by crazeman87** [daydreaming666/Amenoma#20]
This is more informational for people running into this issue as I think this is a issue with the Genshin program itself. 

If you have a ultrawide monitor/resolution, the artifact column will be at 6 even after you change it to 1600x900 (or any other resolution at that ratio).

In order to fix it, you must change the resolution to 1600x900, close and restart the game completely. After restarting, the artifact column will be at 7.

**Comment by Atem83** [comment]
I want to add an important information for people like me who people Genshin on PC with a controller.
If you want for the tool to work, you need to set Control Type to Keyboard in your parameters.

Indeed, if your Control Type is on Controller, the number of rows and columns will be 6 and 9 instead of 5 and 8 even if you set the resolution to 1600x900.
+ the mouse will not work in the Genshin Impact window, so the Amenoma scanning tool will not be able to work.

I hope that @daydreaming666 could add this information in the README_en file.

**Comment by daydreaming666** [comment]
Well, I'll add these helpful infomations to Q&A. Thanks a lot.
